---
- name: Configure nginx virtual hosts
  hosts: webservers
  become: true

  vars:
    vhosts:
      - site1.local
      - site2.local
      - site3.local

  tasks:
    - name: Configure vhosts
      include_role:
        name: nginx_vhost
      loop: "{{ vhosts }}"
      loop_control:
        loop_var: vhost_name